### ISSUE TITLE
Description of lab doesn't match with files

### ISSUE THREAD

**Issue by ioanma** [learn-co-students/jsdom-mod-document-domcontentloaded-lab-qa-internal#1]
"If you take a look at index-demo.html, you'll notice we have event-handling code JavaScript code written at the bottom."
- There is no JS inside index-demo.html.

"Next, move this code into a new file called script.js. Include script.js in the <head> of index-demo.html. "
- See above. Also, there's already a script.js file referenced in index-demo.html so why not add any JS code in there?

**Comment by sgharms** [comment]
1. Agreed, restored.
2. Point is to demo from JS script in index.html in tags _to_ script included with tags.
